buildroot: optee_client_ext: chmod and chown /dev/tpm0
If /dev/tpm0 exists, chmod and chown it so tee-supplicant open and use
it.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

diff --git a/br-ext/package/optee_client_ext/S30optee b/br-ext/package/optee_client_ext/S30optee
--- a/br-ext/package/optee_client_ext/S30optee
+++ b/br-ext/package/optee_client_ext/S30optee
@@ -28,6 +28,17 @@ start() {
 		echo "FAIL"
 		return "$status"
 	fi
+	if [ -e /dev/tpm0 ]; then
+		printf 'Set permissions on %s: ' "/dev/tpm0"
+		chown root:tee /dev/tpm0 && chmod 0660 /dev/tpm0
+		status=$?
+		if [ "$status" -eq 0 ]; then
+			echo "OK"
+		else
+			echo "FAIL"
+			return "$status"
+		fi
+	fi
 	printf 'Starting %s: ' "$DAEMON"
 	start-stop-daemon -S -q -p "$PIDFILE" -c tee -x "$DAEMON_PATH/$DAEMON" \
 		-- $DAEMON_ARGS
